### ISSUE TITLE
Add support for other coordinate types

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/variation-normalization#122]

**Comment by korikuzma** [comment]
- [ ] “m.” for a mitochondrial DNA reference sequence
- [ ] “n.” for a non-coding DNA reference sequence
- [ ] “o.” for a circular genomic reference sequence
- [ ] “r.” for an RNA reference sequence (transcript)

**Comment by korikuzma** [comment]
> * [ ]  “m.” for a mitochondrial DNA reference sequence[ ]  “n.” for a non-coding DNA reference sequence[ ]  “o.” for a circular genomic reference sequence[ ]  “r.” for an RNA reference sequence (transcript)

I agree that eventually we'll want to support, but these should have their own issues using the issue templates
