### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/variation-normalization#163]

**Comment by korikuzma** [comment]
Still todo:
- [ ] DRY
- [ ] Might look to see about removing AltType and seeing if we can use an existing field in the models. Also think I may remove CoordinateType and just use MoleculeContext. Although I think molecule context is being removed once we move to 2.0-alpha (at least I don't see it in the schema yet). Original comment [here](https://github.com/cancervariants/variation-normalization/pull/474#issuecomment-1661040623).
- [ ] Add comment about dups not being supported for c. representation until https://github.com/cancervariants/variation-normalization/issues/187 . Should also check that these genomic -> c representation have tests. Original comment [here](https://github.com/cancervariants/variation-normalization/pull/474#discussion_r1281792136)
- [ ] Remove assert isinstance(q, str) from tests
- [ ] Remove pyliftover dependency. Original comment [here](https://github.com/cancervariants/variation-normalization/pull/474#discussion_r1282196569)
- [ ] Update dup/del base add pos param. Original comment [here](https://github.com/cancervariants/variation-normalization/pull/474#pullrequestreview-1564252723)
